version: '2'
services:
    bigchaindbjhipster-app:
        image: bigchaindbjhipster
        external_links:
            - bigchaindbjhipster-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=bigchaindbjhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bigchaindbjhipster-mongodb:
        extends:
            file: mongodb.yml
            service: bigchaindbjhipster-mongodb
