version: '2'
services:
    rethinkdb:
        container_name: bigchaindb
        image: bigchaindb/bigchaindb:0.6.0
        ports:
            - "28017:28017"
            - "29017:29017"
            - "59984:9984"
            - "58080:8080"
        volumes:
             - ~/bigchaindb_docker:/data
        # 59984 port is for api
        
# To initialize bigchaindb docker image run command:
# docker run --rm -v "$HOME/bigchaindb_docker:/data" -ti bigchaindb/bigchaindb -y configure

