version: '2'
services:
    bigchaindbjhipster-mongodb:
        container_name: bigchaindbjhipster-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/bigchaindbjhipster/mongodb/:/data/db/
